var props = {
  // This can have nested stuff, arrays, etc.
  modules: {1 : 'about',
            2 : 'education',
            3 : 'experience',
            4 : 'contact',
            5 : 'website-design',
            6 : 'login',
            7 : 'sign-up',
            8 : 'logged-in',
            9 : 'logged-out',
            10 : 'admin'},
  tabList:{1 : {modules: [{id : 1, name: 'About'}]},
           2 : {modules: [{id : 2, name : 'Education'}]},
           3 : {modules: [{id : 3, name :'Experience'}]},
           4 : {modules: [{id : 4, name : 'Contact'}]},
           5 : {modules: [{id : 5, name : 'Website Design'}]},
           6 : {modules: []},
           7 : {modules: []},
           8 : {modules: []},
           9 : {modules: []},
           10: {modules: []}},
  modulesWithTables : {1 : {display : false},
                       2 : {display : false},
                       3 : {display : false},
                       4 : {display : false,
                            tableName : 'contact-table'},
                       5 : {display : false},
                       6 : {display : false},
                       7 : {display : false},
                       8 : {display : false},
                       9 : {display : false},
                       10: {display : false}},
  text : {
    TXT_SUCCESS_MSG : 'Operation Completed Successfully!',
    TXT_SUCCESS_HEAD : 'Success!',
    TXT_FAILURE_MSG : 'Operation Failed.',
    TXT_SUBMIT_BTN : 'Submit',
    TXT_SAVE_BTN : 'Save',
    TXT_CANCEL_BTN : 'Cancel',
    TXT_BTN_EXIT : 'Exit'
  },
  websiteName : "Griffin",
  websiteHeader : "Griffin Web App",
  adminLoginCredentials : {username : "brad.raymond.griffin@gmail.com",
                           password : "q1w2e3r4",
                           role : "admin"}
}
