props = {
  // This can have nested stuff, arrays, etc.
  modules: {1 : 'about',
            2 : 'education',
            3 : 'experience',
            4 : 'contact',
            5 : 'website-design',
            6 : 'login',
            7 : 'sign-up',
            8 : 'logged-in',
            9 : 'logged-out'},
  modulesWithTables : {1 : {false},
                       2 : {false},
                       3 : {false},
                       4 : {display : true,
                            tableName : 'contact-table'},
                       5 : {false},
                       6 : {false},
                       7 : {false},
                       8 : {false},
                       9 : {false}},
  text : {
    TXT_SUCCESS_MSG : 'Operation Completed Successfully!',
    TXT_SUCCESS_HEAD : 'Success!',
    TXT_FAILURE_MSG : 'Operation Failed.',
    TXT_SUBMIT_BTN : 'Submit',
    TXT_SAVE_BTN : 'Save',
    TXT_CANCEL_BTN : 'Cancel',
    TXT_BTN_EXIT : 'Exit'
  },
  websiteName : "Griffin",
  websiteHeader : "Griffin Web App",
  adminLoginCredentials : {username : "brad.raymond.griffin@gmail.com",
                           password : "q1w2e3r4"}
}
