# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'deps'
      prefix-development: 'deps-dev'
      include: 'scope'
    ignore:
      - dependency-name: '*'
    open-pull-requests-limit: 5
    allow:
      - dependency-name: '*'
    group:
      - group-name: 'all-dependencies'
        patterns:
          - '*'
        exclude-updates:
          - dependency-name: 'eslint'
        labels:
          - 'dependencies'
          - 'grouped'
    reviewers:
      - 'bradleyrgriffin'
    assignees:
      - 'bradleyrgriffin'
    automerge: true
    versioning-strategy: 'increase'
